# Generated by Django 4.0.3 on 2022-03-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThdDin',
            fields=[
                ('thdid', models.BigIntegerField(db_column='ThdID', primary_key=True, serialize=False)),
                ('thdcd', models.DateTimeField(db_column='ThdCD')),
                ('uniqueid', models.BigIntegerField(db_column='uniqueID')),
                ('casenumber', models.CharField(db_column='CaseNumber', max_length=255)),
                ('customer', models.CharField(blank=True, db_column='Customer', max_length=255, null=True)),
                ('createdon', models.DateTimeField(db_column='CreatedOn')),
                ('businessunit', models.CharField(db_column='BusinessUnit', max_length=255)),
                ('packagename', models.CharField(blank=True, db_column='PackageName', max_length=255, null=True)),
                ('subarea', models.CharField(db_column='SubArea', max_length=255)),
                ('serviceid', models.BigIntegerField(blank=True, db_column='ServiceID', null=True)),
                ('networktype', models.CharField(blank=True, db_column='NetworkType', max_length=255, null=True)),
                ('transceiverid', models.CharField(blank=True, db_column='TransceiverID', max_length=255, null=True)),
                ('complaintaddress', models.TextField(blank=True, db_column='ComplaintAddress', null=True)),
                ('rootcause1', models.CharField(db_column='RootCause1', max_length=255)),
                ('rootcause2', models.CharField(db_column='RootCause2', max_length=255)),
                ('complaintlocationlatitude', models.FloatField(blank=True, db_column='ComplaintLocationLatitude', null=True)),
                ('complaintlocationlongitude', models.FloatField(blank=True, db_column='ComplaintLocationLongitude', null=True)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=255, null=True)),
                ('siteid', models.CharField(blank=True, db_column='SiteID', max_length=255, null=True)),
                ('packagetype', models.CharField(db_column='Packagetype', max_length=255)),
                ('casetype', models.CharField(db_column='CaseType', max_length=255)),
                ('week', models.IntegerField(db_column='Week')),
                ('month', models.IntegerField(db_column='Month')),
                ('year', models.IntegerField(db_column='Year')),
                ('caseaging', models.IntegerField(db_column='CaseAging')),
                ('marphology', models.CharField(blank=True, db_column='Marphology', max_length=255, null=True)),
                ('cluster', models.CharField(blank=True, db_column='Cluster', max_length=255, null=True)),
                ('statesite', models.CharField(blank=True, db_column='StateSite', max_length=255, null=True)),
                ('casecategory', models.CharField(db_column='CaseCategory', max_length=255)),
                ('rootcausesummarize', models.CharField(db_column='RootCauseSummarize', max_length=255)),
                ('projectsiteid', models.CharField(blank=True, db_column='ProjectSiteID', max_length=255, null=True)),
                ('projecttype', models.CharField(blank=True, db_column='Projecttype', max_length=255, null=True)),
                ('projectstatus', models.CharField(blank=True, db_column='Projectstatus', max_length=255, null=True)),
                ('cpmplanner', models.CharField(blank=True, db_column='CPMPlanner', max_length=255, null=True)),
                ('rfsdate', models.DateTimeField(blank=True, db_column='RFSdate', null=True)),
                ('resolvedaging', models.IntegerField(blank=True, db_column='ResolvedAging', null=True)),
                ('nonrfs', models.DateTimeField(blank=True, db_column='NONRFS', null=True)),
                ('rfs', models.DateTimeField(blank=True, db_column='RFS', null=True)),
                ('aging', models.CharField(blank=True, db_column='Aging', max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, db_column='Vendor', max_length=255, null=True)),
                ('siteidplanner', models.CharField(blank=True, db_column='SiteIDPlanner', max_length=255, null=True)),
                ('clusteraddress', models.TextField(blank=True, db_column='ClusterAddress', null=True)),
                ('sitelat', models.FloatField(blank=True, db_column='SiteLat', null=True)),
                ('sitelong', models.FloatField(blank=True, db_column='SiteLong', null=True)),
                ('faultylocationlatlong', models.CharField(blank=True, db_column='FaultyLocationLatlong', max_length=255, null=True)),
            ],
            options={
                'db_table': 'thd_din',
            },
        ),
    ]
